language: python
services: docker
python:
        "3.8"


script:
        - docker pull blang/latex
        - python build.py

deploy:
        provider: releases
        api_key: $RELEASES_TOKEN
        
        file: 
                - output/*
        
        on:
                tags: true
        
        edge: true
